# Generated by Django 5.0.3 on 2024-03-28 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FaqAnswer',
            fields=[
                ('answer_id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='FAQ ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('answer', models.TextField(max_length=1000, verbose_name='Answer')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
            ],
        ),
    ]
