# Generated by Django 5.0.3 on 2024-03-31 16:32

from django.db import migrations


def insert_faq_data(apps, schema_editor):
    FaqAnswer = apps.get_model("api", "FaqAnswer")

    faq_elements = [
        {
            "title": "How does AI improve efficiency in tasks?",
            "content": "AI can automate complex tasks, saving time and reducing error rates.",
        },
        {
            "title": "Can AI adapt and learn over time?",
            "content": "AI algorithms adapt through progressive learning to enhance data analysis.",
        },
        {
            "title": "What role does AI play in data analysis?",
            "content": "Intelligent systems can analyze big data patterns to inform decisions.",
        },
        {
            "title": "What are the ethical considerations of AI?",
            "content": "Ethical AI use respects privacy and ensures unbiased decision-making.",
        },
        {
            "title": "How does AI contribute to predictive maintenance?",
            "content": "AI assists in predictive maintenance, improving equipment longevity.",
        },
        {
            "title": "Can AI be creative?",
            "content": "AI's deep learning can create art, music, and realistic simulations.",
        },
        {
            "title": "Does AI assist in real-time language translation?",
            "content": "Advanced AI provides real-time language translation and transcription.",
        },
    ]

    for faq in faq_elements:
        FaqAnswer.objects.create(title=faq["title"], content=faq["content"])


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [migrations.RunPython(insert_faq_data)]
