# Generated by Django 5.0.3 on 2024-04-01 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_insert_faq_data"),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerCompany',
            fields=[
                ('company_id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Company ID')),
                ('company_name', models.CharField(max_length=255, verbose_name='Company name')),
                ('company_logo', models.URLField(verbose_name='Company logo')),
                ('company_website', models.URLField(verbose_name='Company website')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
            ],
        ),
    ]
