# Generated by Django 5.0.3 on 2024-04-01 17:57

from django.db import migrations


def insert_partner_companies(apps, schema_editor):
    PartnerCompany = apps.get_model("api", "PartnerCompany")

    partner_companies = [
        {
            "company_name": "Facebook",
            "company_logo": "https://i.postimg.cc/fyswZFcp/facebook.png",
            "company_website": "https://www.facebook.com/",
        },
        {
            "company_name": "Google",
            "company_website": "https://about.google/",
            "company_logo": "https://i.postimg.cc/T3cLLV7Z/google.png",
        },
        {
            "company_name": "Amazon",
            "company_website": "https://www.amazon.com/",
            "company_logo": "https://i.postimg.cc/ydtZPVz9/amazon.png",
        },
        {
            "company_name": "Slack",
            "company_website": "https://slack.com/",
            "company_logo": "https://i.postimg.cc/kghCpDB2/slack.png",
        },
        {
            "company_name": "GitKraken",
            "company_website": "https://www.gitkraken.com/",
            "company_logo": "https://i.postimg.cc/mg41gXwY/gitkraken.png",
        },
        {
            "company_name": "Microsoft",
            "company_website": "https://www.microsoft.com/en-us/",
            "company_logo": "https://i.postimg.cc/BbWQwb7T/microsoft.png",
        },
        {
            "company_name": "Dropbox",
            "company_website": "https://www.dropbox.com/",
            "company_logo": "https://i.postimg.cc/sgT1mVYX/dropbox.png",
        },
        {
            "company_name": "Ebay",
            "company_website": "https://www.ebay.com/",
            "company_logo": "https://i.postimg.cc/6Q76hC6j/Ebay.png",
        },
        {
            "company_name": "Intel",
            "company_website": "https://www.intel.com/",
            "company_logo": "https://i.postimg.cc/wTX3Z5p7/intel.png",
        },
        {
            "company_name": "Netflix",
            "company_website": "https://www.netflix.com/",
            "company_logo": "https://i.postimg.cc/QxL7KxmZ/netflix.webp",
        },
    ]

    for partner_company in partner_companies:
        PartnerCompany.objects.create(
            company_name=partner_company["company_name"],
            company_logo=partner_company["company_logo"],
            company_website=partner_company["company_website"],
        )


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_partnercompany"),
    ]

    operations = [
        migrations.RunPython(insert_partner_companies),
    ]
