# Generated by Django 5.0.3 on 2024-04-08 19:24

from django.db import migrations


def insert_predefined_plans(apps, schema_editor):
    Plan = apps.get_model("api", "Plan")

    predefined_plans = [
        {
            "plan": "Free Trial",
            "description": "Perfect for testing our features",
            "cost": 0,
            "button_text": "Start free trial",
        },
        {
            "plan": "Pro",
            "description": "For professional users",
            "cost": 80,
            "button_text": "Get started",
        },
        {
            "plan": "Business",
            "description": "For medium and large businesses",
            "cost": 200,
            "button_text": "Contact Sales",
        },
    ]

    for plan_info in predefined_plans:
        Plan.objects.create(**plan_info)


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0006_plan_planadvantage"),
    ]

    operations = [migrations.RunPython(insert_predefined_plans)]
