# Generated by Django 5.0.3 on 2024-04-08 19:24

from django.db import migrations


def insert_predefined_plans(apps, schema_editor):
    PricingPlan = apps.get_model("api", "PricingPlan")

    predefined_plans = [
        {
            "plan": "Hobby",
            "description": "Perfect for testing our features",
            "cost": 5,
            "button_text": "Open up Hobby",
        },
        {
            "plan": "Pro",
            "description": "For professional users",
            "cost": 20,
            "button_text": "Get started",
        },
        {
            "plan": "Business",
            "description": "For medium and large businesses",
            "cost": 40,
            "button_text": "Contact Sales",
        },
    ]

    for plan_info in predefined_plans:
        PricingPlan.objects.create(**plan_info)


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0006_plan_planadvantage"),
    ]

    operations = [migrations.RunPython(insert_predefined_plans)]
