# Generated by Django 5.0.3 on 2024-04-08 19:58

from django.db import migrations


def insert_advantages_for_plan(plan_name: str, advantages: list, apps):
    Plan = apps.get_model("api", "Plan")
    PlanAdvantage = apps.get_model("api", "PlanAdvantage")

    plan = Plan.objects.get(plan=plan_name)

    for advantage in advantages:
        PlanAdvantage.objects.create(plan=plan, **advantage)


def insert_plans_advantages(apps, schema_editor):
    freeTrialAdvantages = [
        {"advantage": "🔍 Access to basic AI models"},
        {"advantage": "📧 Basic support via email"},
        {"advantage": "3️⃣🤖 Up to 3 projects with AI integration"},
        {"advantage": "🏛️ Community forum access"},
    ]

    ProAdvantages = [
        {"advantage": "🚀 Advanced AI model access"},
        {"advantage": "✉️🔝 Priority email support"},
        {"advantage": "🔟🧠 Up to 10 projects with enhanced AI features"},
        {"advantage": "🔌 API access with limited requests"},
        {"advantage": "🛠️🤖 Custom AI model training (up to 1 model)"},
        {"advantage": "🖥️🎓 Access to AI and software development webinars"},
    ]

    BusinessAdvantages = [
        {"advantage": "💎 Premium AI model access"},
        {"advantage": "🕒💼 24/7 Premium support with dedicated manager"},
        {"advantage": "∞🤖 Unlimited projects with full AI capabilities"},
        {"advantage": "⚡🔌 High-priority API access with increased request limits"},
        {"advantage": "🏋️‍♂️🤖×5 Custom AI model training (up to 5 models)"},
        {"advantage": "🎁🆕 Early access to new features and AI models"},
        {"advantage": "📜⏱️ SLA guarantees and uptime commitments"},
        {"advantage": "🎓🔄 Onboarding and continuous training sessions for your team"},
    ]

    insert_advantages_for_plan(
        plan_name="Free Trial", advantages=freeTrialAdvantages, apps=apps
    )
    insert_advantages_for_plan(plan_name="Pro", advantages=ProAdvantages, apps=apps)
    insert_advantages_for_plan(
        plan_name="Business", advantages=BusinessAdvantages, apps=apps
    )


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0007_insert_predefined_plans"),
    ]

    operations = [migrations.RunPython(insert_plans_advantages)]
