version: "3.9"

services:
  database:
    container_name: postgres
    image: postgres:13-alpine
    ports:
      - "2311:5432"
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
    command: "postgres -c max_connections=150
              -c shared_buffers=512MB -c effective_cache_size=1536MB
              -c maintenance_work_mem=128MB -c checkpoint_completion_target=0.9 -c wal_buffers=16MB
              -c default_statistics_target=100 -c random_page_cost=1.1 -c effective_io_concurrency=200
              -c work_mem=3495kB -c min_wal_size=1GB -c max_wal_size=4GB -c max_worker_processes=2
              -c max_parallel_workers_per_gather=1 -c max_parallel_workers=2 -c max_parallel_maintenance_workers=1"
    env_file:
      - ".env"
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

  rest-api:
    container_name: rest-api
    image: django-app
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: "python manage.py runserver 0.0.0.0:6020"
    restart: always
    env_file:
      - ".env"
    ports:
      - "6020:6020"
    links:
      - "database"
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

volumes:
  pgdata: {}
  cache: {}
